name: hello actions
  on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main
    workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello actions
        run: echo "Hello Actions !!"
        shell: bash

   goodbye:
     runs-on: ubuntu-latest
     steps:
       - name: goodbye actions
         run: echo "Goodbye Actions"
         shell: bash
   
